# Generated by Django 3.2.5 on 2021-08-14 06:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_engine', '0002_alter_blogmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 6, 36, 10, 463704, tzinfo=utc)),
        ),
    ]
