# Generated by Django 3.2.5 on 2021-08-14 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_engine', '0003_alter_blogmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 7, 37, 7, 190129)),
        ),
    ]
