# Generated by Django 3.2.6 on 2021-09-13 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_engine', '0004_alter_blogmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='body',
            field=models.TextField(default='whatever...', null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 12, 18, 30, 26, 442015)),
        ),
    ]
